### ISSUE TITLE
Any way to fetch recovery key shares

### ISSUE THREAD

**Issue by omadawn** [cucxabong/hashicorp-vault-utils#1]
Have just tried your tool for fetching the vault recovery key out of consul.

It _appears_ to be working however a vault init gives me results like: (bogus values)

$ vault operator init
Recovery Key 1: hs8STRrBD21434912340432423442SjFHKaSvH8QHY
Recovery Key 2: j34Z234932043sdfliweG5f1fK81k+4JewhhxeaZeGFxhL
Recovery Key 3: +0wX6oOdluIc8Usm2sf921sffssmu8IwsQzyAPcXiy0h
Recovery Key 4: JLX27y6M4tdC1nhcMModki23c9flsdfk22+r42ssiSaVEP
Recovery Key 5: jjgz+mE9rm/AGv1kg+Xldsjwesdiwelsdi21324H6wc3xlq3y

But your tool only outputs a single value like: (bogus value)

wK9nVh/7wqVNevilwerif234vsgFIUVF83VEp1vgJ0=

If I understand your article this is the base64 encoded version of the actual recovery key and the above are shamir's slices of the recovery key. 

But to use it I need the slices. Is there a way to get that output.

**Comment by cucxabong** [comment]
My tool assume that you have only 1 share of recovery key, dont think it will work with your case. Do you use auto-unseal feature?

**Comment by omadawn** [comment]
I do.
Actually this is doable. Your tool is fetching the actual recovery key which is stored in the database. The "Recovery keys" that `vault operator init` spits out are shamir's secret shares of that recovery key. 
Apparently these aren't stored in the database at all. Only the actual key. 
I was able to write a small golang tool which takes the output from your command and splits it into recovery shares. Then I was able to re-key using those shares.

I hope to submit an MR to add this functionality in the not too distant future.

**Comment by omadawn** [comment]
If I don't come up with the time to create the MR the sourcecode I used to test splitting your output is only a few lines. 

```
package main

import (
	"encoding/base64"
	"fmt"
	"github.com/hashicorp/vault/shamir"
	"gitlab.com/theuberlab/thoth/log"
)

func main() {

	decodedKey, err := base64.StdEncoding.DecodeString("<output of hashicorp-vault-utils>")
	if err != nil {
		log.Fatalln("Error creating shares")
	}


	result, err := shamir.Split(decodedKey, 5, 3)
	if err != nil {
		log.Fatalln("Error creating shares")
	}

	for _, value := range result {
		fmt.Printf("Value: %s\n", base64.StdEncoding.EncodeToString(value))
	}
}
```

**Comment by omadawn** [comment]
Oh and thank you very much for publishing this tool.

**Comment by cucxabong** [comment]
Hi @omadawn 
Thank you for your suggestion, I have added options to specify `--recovery-shares` and `--recovery-threshold` to split recovery key. If user omit those options, this tool will parse recovery config file in backend to split they key

**Comment by omadawn** [comment]
Well I guess I won't need to submit a PR then. ^_^
thanks

--
Aaron Forster
Phone: (206) 465-1936
Email: ***@***.***
